server:
  port: 8080

spring:
  datasource:
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    #url: jdbc:h2:file:/home/siim/Desktop/codemaster/app-db;AUTO_SERVER=TRUE
    #driverClassName: org.h2.Driver
    #username: sa
    #password: sa
    url: jdbc:postgresql://localhost:5432/app
    driverClassName: org.postgresql.Driver
    username: app
    password: app
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    #generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    enabled: false